version: '3'
services:
  bot:
    build: .
    depends_on:
    - voicevox
    environment:
    - ENDPOINT=http://voicevox
    - TOKEN=${TOKEN}
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
    - "50021:50021"
